run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - unused
    - structcheck
    - ineffassign
    - revive
    - gocritic
  disable:
    - maligned

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
