stages:
  - test
  - contract
  - bench

variables:
  NODE_ENV: test

web_unit_tests:
  stage: test
  script:
    - cd services/web
    - npm ci --silent
    - npm run test:unit --silent

web_contract_tests:
  stage: contract
  script:
    - cd services/web
    - npm ci --silent
    - npm run test:contract --silent

web_accessibility:
  stage: contract
  variables:
    PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
  script:
    - cd services/web
    - npm ci --silent
    - npm run e2e:playwright
  allow_failure: false
  timeout: 30m

gitbridge_maven_tests:
  stage: test
  script:
    - cd services/git-bridge
    - mvn -B -q -DskipTests=false test

bench_key_lookup:
  stage: bench
  variables:
    KEY_LOOKUP_P95_MS: "50"
  script:
    - BENCH_OUTPUT=ci/benchmarks/key-lookup-benchmark/out.json BENCH_ITER=${BENCH_ITER:-200} BENCH_CONCURRENCY=${BENCH_CONCURRENCY:-20} BENCH_URL=${BENCH_URL:-http://127.0.0.1:3000/internal/api/ssh-keys/SHA256:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA} node ci/benchmarks/key-lookup-benchmark/bench.js
    - node ci/benchmarks/check-bench-slo.js ci/benchmarks/key-lookup-benchmark/out.json ${KEY_LOOKUP_P95_MS}
  artifacts:
    paths:
      - ci/benchmarks/key-lookup-benchmark/out.json
    expire_in: 1 week
  allow_failure: false

bench_introspection:
  stage: bench
  variables:
    INTROSPECTION_P95_MS: "100"
  script:
    - BENCH_OUTPUT=ci/benchmarks/introspection-benchmark/out.json BENCH_ITER=${BENCH_ITER:-200} BENCH_CONCURRENCY=${BENCH_CONCURRENCY:-20} BENCH_URL=${BENCH_URL:-http://127.0.0.1:3000/internal/api/tokens/introspect} BENCH_TOKEN=${BENCH_TOKEN:-invalid-token} node ci/benchmarks/introspection-benchmark/bench.js
    - node ci/benchmarks/check-bench-slo.js ci/benchmarks/introspection-benchmark/out.json ${INTROSPECTION_P95_MS}
  artifacts:
    paths:
      - ci/benchmarks/introspection-benchmark/out.json
    expire_in: 1 week
  allow_failure: false
