stages:
  - test
  - contract
  - bench

variables:
  NODE_ENV: test

web_unit_tests:
  stage: test
  script:
    - cd services/web
    - npm ci --silent
    - npm run test:unit --silent

web_contract_tests:
  stage: contract
  script:
    - cd services/web
    - npm ci --silent
    - npm run test:contract --silent

gitbridge_maven_tests:
  stage: test
  script:
    - cd services/git-bridge
    - mvn -B -q -DskipTests=false test

bench_key_lookup:
  stage: bench
  script:
    - node ci/benchmarks/key-lookup-benchmark/bench.js
  allow_failure: true

bench_introspection:
  stage: bench
  script:
    - node ci/benchmarks/introspection-benchmark/bench.js
  allow_failure: true
