# Dockerfile template for {{SERVICE_NAME}}-go

FROM golang:1.25-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/{{SERVICE_NAME}}-go

FROM scratch
COPY --from=build /bin/{{SERVICE_NAME}}-go /bin/{{SERVICE_NAME}}-go
ENTRYPOINT ["/bin/{{SERVICE_NAME}}-go"]
