openapi: 3.0.3
info:
  title: SSH Key Lookup API (internal)
  version: 1.0.0
paths:
  /internal/api/ssh-keys/{fingerprint}:
    get:
      summary: Lookup userId by SSH public-key fingerprint
      parameters:
        - name: fingerprint
          in: path
          required: true
          schema:
            type: string
            example: "SHA256:abc..."
      responses:
        "200":
          description: Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    description: ObjectId of the owning user
        "404":
          description: Not Found
        "400":
          description: Bad Request (malformed fingerprint)
security:
  - serviceToken: []
components:
  securitySchemes:
    serviceToken:
      type: http
      scheme: bearer
      bearerFormat: ServiceToken
